export const dataObjects = [
  //CHAKRAS
  {
    img: "images/chakras/crown.jpg",
    name: "Crown Chakra",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/chakra modal/crown modal.jpg",
    tags: [
      "crown",
      "head",
      "mind",
      "focus",
      "consciousness",
      "celestial",
      "spirit",
      "chakras",
    ],
  },
  {
    img: "images/chakras/Third eye.jpg",
    name: "Third Eye Chakra",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/chakra modal/third eye modal.jpg",
    tags: [
      "third",
      "eye",
      "intuition",
      "thought",
      "vision",
      "clarity",
      "insight",
      "focus",
      "dream",
      "chakras",
    ],
  },
  {
    img: "images/chakras/Throat.jpg",
    name: "Throat Chakra",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/chakra modal/throat modal.jpg",
    tags: [
      "throat",
      "voice",
      "truth",
      "confidence",
      "communication",
      "affirmation",
      "chakras",
    ],
  },
  {
    img: "images/chakras/heart.jpg",
    name: "Heart Chakra",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/chakra modal/heart modal.jpg",
    tags: [
      "heart",
      "love",
      "care",
      "self care",
      "compassion",
      "relation",
      "self",
      "chakras",
    ],
  },
  {
    img: "images/chakras/solar.jpg",
    name: "Solar Plexus Chakra",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/chakra modal/solar modal.jpg",
    tags: [
      "solar",
      "plexus",
      "power",
      "will",
      "strength",
      "strengthen",
      "manifest",
      "confidence",
      "perseverance",
      "determination",
      "chakras",
    ],
  },
  {
    img: "images/chakras/sacral.jpg",
    name: "Sacral Chakra",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/chakra modal/sacral modal.jpg",
    tags: [
      "sacral",
      "creativity",
      "connection",
      "connecting",
      "relation",
      "sexuality",
      "creation",
      "chakras",
    ],
  },
  {
    img: "images/chakras/root.jpg",
    name: "Root Chakra",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/chakra modal/root modal.jpg",
    tags: [
      "root",
      "survival",
      "safety",
      "ground",
      "protection",
      "persistance",
      "chakras",
    ],
  },
  //CHAKRAS
  //SKIN AND BEAUTY
  {
    img: "images/beauty and skin/aging.jpg",
    name: "Aging",
    models: ["pro"],
    modal: "images/modal content/beauty and skin modal/aging.jpg",
    tags: ["aging", "skin", "beauty", "age", "old", "wrinkle", "wrinkles"],
  },
  {
    img: "images/beauty and skin/hair.jpg",
    name: "Hair",
    models: ["pro"],
    modal: "images/modal content/beauty and skin modal/hair.jpg",
    tags: ["hair", "beauty", "skin", "head", "scalp"],
  },
  {
    img: "images/beauty and skin/Inner beauty.jpg",
    name: "Inner Beauty",
    models: ["pro"],
    modal: "images/modal content/beauty and skin modal/inner beauty.jpg",
    tags: ["inner", "beauty", "skin", "inner beauty"],
  },
  {
    img: "images/beauty and skin/nails.jpg",
    name: "Nail Harmony",
    models: ["pro"],
    modal: "images/modal content/beauty and skin modal/nail harmony.jpg",
    tags: ["nails", "beauty", "skin", "nail"],
  },
  {
    img: "images/beauty and skin/scar harmony local.jpg",
    name: "Scar Harmony Local",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/beauty and skin modal/scar harmony local.jpg",
    tags: ["Scar Harmony Local", "scar", "skin", "beauty", "local", "harmony"],
  },
  {
    img: "images/beauty and skin/scar harmony syst.jpg",
    name: "Scar Harmony Systemic",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/beauty and skin modal/scar harmony system.jpg",
    tags: [
      "Scar Harmony Systemic",
      "scar",
      "skin",
      "beauty",
      "systemic",
      "harmony",
      "asthma",
    ],
  },
  {
    img: "images/beauty and skin/skin elasticity.jpg",
    name: "Skin Elasticity",
    models: ["pro"],
    modal: "images/modal content/beauty and skin modal/skin energy.jpg",
    tags: ["Skin Elasticity", "skin", "elasticity", "beauty", "elastic"],
  },
  {
    img: "images/beauty and skin/skin harmony local.jpg",
    name: "Skin Harmony Local",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/beauty and skin modal/skin harmony local.jpg",
    tags: [
      "Skin Harmony Local",
      "skin",
      "beauty",
      "local",
      "harmony",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  {
    img: "images/beauty and skin/skin harmony syst.jpg",
    name: "Skin Harmony Systemic",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/beauty and skin modal/skin harmony system.jpg",
    tags: [
      "Skin Harmony Systemic",
      "skin",
      "harmony",
      "beauty",
      "systemic",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  {
    img: "images/beauty and skin/skin impurity syst.jpg",
    name: "Skin Impurity Systemic",
    models: ["all", "plus", "pro"],
    modal:
      "images/modal content/beauty and skin modal/skin impruity system.jpg",
    tags: [
      "Skin Impurity Systemic",
      "skin",
      "impurity",
      "beauty",
      "systemic",
      "purity",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  {
    img: "images/beauty and skin/skin.jpg",
    name: "Beauty Skin",
    models: ["pro"],
    modal: "images/modal content/beauty and skin modal/skin.jpg",
    tags: ["beauty", "skin", "itching", "rash", "inflammation"],
  },
  //SKIN AND BEAUTY
  //BIOENERGETIC DEFENSE
  {
    img: "images/bioenergetic defense/cell.jpg",
    name: "Bio Defense Cell",
    models: ["pro"],
    modal: "images/modal content/bioenergetic defense modal/cell.jpg",
    tags: ["cell", "cells", "bioenergetic defense"],
  },
  {
    img: "images/bioenergetic defense/electrosensitivity.jpg",
    name: "Electrosensitivity",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic defense modal/electrosensitivity.jpg",
    tags: ["electrosensitivity", "bioenergetic defense"],
  },
  {
    img: "images/bioenergetic defense/general protection.jpg",
    name: "General Protection",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic defense modal/general protection.jpg",
    tags: [
      "general protection",
      "general",
      "protection",
      "bioenergetic defense",
    ],
  },
  {
    img: "images/bioenergetic defense/geopathy.jpg",
    name: "Geopathy",
    models: ["pro"],
    modal: "images/modal content/bioenergetic defense modal/geopathy.jpg",
    tags: ["geopathy", "bioenergetic defense"],
  },
  {
    img: "images/bioenergetic defense/mental.jpg",
    name: "Mental",
    models: ["pro"],
    modal: "images/modal content/bioenergetic defense modal/mental.jpg",
    tags: ["mental", "bioenergetic defense", "mind"],
  },
  {
    img: "images/bioenergetic defense/planets.jpg",
    name: "Planets",
    models: ["pro"],
    modal: "images/modal content/bioenergetic defense modal/planets.jpg",
    tags: ["planets", "bioenergetic defense"],
  },
  {
    img: "images/bioenergetic defense/sleeping.jpg",
    name: "Sleeping",
    models: ["pro"],
    modal: "images/modal content/bioenergetic defense modal/sleeping.jpg",
    tags: ["sleeping", "bioenergetic defense"],
  },
  {
    img: "images/bioenergetic defense/subtle.jpg",
    name: "Subtle",
    models: ["pro"],
    modal: "images/modal content/bioenergetic defense modal/subtle.jpg",
    tags: ["subtle", "bioenergetic defense"],
  },
  //BIOENERGETIC DEFENSE
  //BIOENERGETIC HARMONY 1
  {
    img: "images/bioenergetic harmony 1/bio harmony circulation.jpg",
    name: "Bio Harmony Circulation",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 1 modal/bio harmony circulation.jpg",
    tags: [
      "bioenergetic harmony",
      "blood",
      "circulation",
      "asthma",
      "body",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/defense.jpg",
    name: "Defense",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 1 modal/defence.jpg",
    tags: [
      "bioenergetic harmony",
      "defense",
      "shield",
      "resistance",
      "immunity",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/eyes harmony.jpg",
    name: "Eyes Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 1 modal/eyes harmony.jpg",
    tags: [
      "bioenergetic harmony",
      "eyes",
      "sight",
      "vision",
      "see",
      "look",
      "harmony",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/flexibility.jpg",
    name: "Flexibility",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 1 modal/flexibilty.jpg",
    tags: [
      "bioenergetic harmony",
      "flexibility",
      "flexible",
      "stretch",
      "move",
      "body",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/for mature women.jpg",
    name: "For Mature Women",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 1 modal/for mature women.jpg",
    tags: [
      "bioenergetic harmony",
      "female",
      "feminine",
      "for",
      "mature",
      "women",
      "woman",
      "lady",
      "ladies",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/for women.jpg",
    name: "For Women",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 1 modal/for women.jpg",
    tags: [
      "bioenergetic harmony",
      "female",
      "feminine",
      "for",
      "women",
      "woman",
      "lady",
      "ladies",
      "cramps",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/hormone harmony.jpg",
    name: "Hormone Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 1 modal/hormone harmony.jpg",
    tags: ["bioenergetic harmony", "hormone", "harmony"],
  },
  {
    img: "images/bioenergetic harmony 1/intestine harmony.jpg",
    name: "Intestine Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 1 modal/intestine harmony.jpg",
    tags: [
      "bioenergetic harmony",
      "intestine",
      "harmony",
      "gut",
      "gastrointestinal",
      "gi",
      "digest",
      "digestion",
      "candida",
      "yeast",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/nerve harmony.jpg",
    name: "Bio Harmony Nerve Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 1 modal/nerve harmony.jpg",
    tags: ["bioenergetic harmony", "nerve", "harmony", "inflammation"],
  },
  {
    img: "images/bioenergetic harmony 1/potency.jpg",
    name: "Potency",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 1 modal/potency.jpg",
    tags: ["bioenergetic harmony", "potency", "potent"],
  },
  {
    img: "images/bioenergetic harmony 1/sensitivity.jpg",
    name: "Sensitivity",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 1 modal/sensitivity.jpg",
    tags: [
      "bioenergetic harmony",
      "sensitivity",
      "sensitive",
      "asthma",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/shiver.jpg",
    name: "Shiver",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 1 modal/shiver.jpg",
    tags: ["bioenergetic harmony", "shiver", "cold", "chill"],
  },
  //BIOENERGETIC HARMONY 1
  //BIOENERGETIC 2
  {
    img: "images/bioenergetic harmony 2/bacteria harmony.jpg",
    name: "Bacteria Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 2 modal/bacteria harmony.jpg",
    tags: ["bioenergetic harmony", "bacteria", "harmony", "gut"],
  },
  {
    img: "images/bioenergetic harmony 2/food imbalance.jpg",
    name: "Food Imbalance",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 2 modal/food imbalances.jpg",
    tags: [
      "bioenergetic harmony",
      "food",
      "imbalance",
      "digestion",
      "candida",
      "yeast",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/gastrointestinal harmony.jpg",
    name: "Gastrointestinal Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 2 modal/gastrointestinal harmony.jpg",
    tags: [
      "bioenergetic harmony",
      "gastrointestinal",
      "harmony",
      "gut",
      "digestion",
      "digest",
      "candida",
      "yeast",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/head harmony.jpg",
    name: "Head Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 2 modal/head harmony.jpg",
    tags: [
      "bioenergetic harmony",
      "head",
      "harmony",
      "headache",
      "brain",
      "mind",
      "fog",
      "clarity",
      "focus",
      "cold",
      "oral",
      "teeth",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/impurities.jpg",
    name: "Impurities",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 2 modal/impurities.jpg",
    tags: [
      "bioenergetic harmony",
      "impurities",
      "pure",
      "purify",
      "clean",
      "clear",
      "cleanse",
      "remove",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/joints-bone harmony.jpg",
    name: "Joints and Bone Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 2 modal/joints-bones harmony.jpg",
    tags: [
      "bioenergetic harmony",
      "joints",
      "bone",
      "harmony",
      "skeletal",
      "structure",
      "frame",
      "foundation",
      "flexibility",
      "body",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/liver harmony.jpg",
    name: "Liver Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 2 modal/liver harmony.jpg",
    tags: [
      "bioenergetic harmony",
      "liver",
      "harmony",
      "cleanse",
      "clean",
      "fortify",
      "renew",
      "detox",
      "organ",
      "organs",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/lung harmony.jpg",
    name: "Lung Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic harmony 2 modal/lung harmony.jpg",
    tags: [
      "bioenergetic harmony",
      "lung",
      "harmony",
      "cleanse",
      "clean",
      "fortify",
      "renew",
      "detox",
      "breath",
      "breathing",
      "asthma",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/prostate harmony.jpg",
    name: "Prostate Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 2 modal/prostate harmony.jpg",
    tags: [
      "bioenergetic harmony",
      "prostate",
      "harmony",
      "fortify",
      "renew",
      "organ",
      "organs",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/sciatica nerve harmony local.jpg",
    name: "Sciatica Nerve Harmony Local",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 2 modal/sciatica nerve harmony local.jpg",
    tags: [
      "bioenergetic harmony",
      "sciatica",
      "nerve",
      "harmony",
      "local",
      "inflammation",
      "back",
      "pain",
      "back pain",
      "leg pain",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/thyroid gland harmony.jpg",
    name: "Thyroid Gland Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 2 modal/thyroid glan harmony.jpg",
    tags: ["bioenergetic harmony", "thyroid", "gland", "harmony"],
  },
  {
    img: "images/bioenergetic harmony 2/tonsil harmony.jpg",
    name: "Tonsil Harmony",
    models: ["all", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic harmony 2 modal/tonsil harmony.jpg",
    tags: ["bioenergetic harmony", "tonsil", "harmony", "mouth", "throat"],
  },
  //BIOENERGETIC 2
  //BIOENERGETIC SUPPORT
  {
    img: "images/bioenergetic support/bioenergetic boost.jpg",
    name: "Bioenergetic Boost",
    models: ["all", "gold", "holistic", "plus", "pro"],
    modal:
      "images/modal content/bioenergetic support modal/bioenergetic boost.jpg",
    tags: [
      "bioenergetic support",
      "boost",
      "cold",
      "bioenergetic boost",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic support/coherence.jpg",
    name: "Coherence",
    models: ["all", "gold", "holistic", "plus", "pro"],
    modal: "images/modal content/bioenergetic support modal/coherence.jpg",
    tags: [
      "bioenergetic support",
      "coherence",
      "mind",
      "brain",
      "focus",
      "learn",
      "learning",
      "anxiety",
    ],
  },
  //BIOENERGETIC SUPPORT
  //BIOENERGETIC VITALIZATION
  {
    img: "images/bioenergetic vitalization/bones.jpg",
    name: "Bones",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/bone harmony.jpg",
    tags: ["bones", "bioenergetic vitalization"],
  },
  {
    img: "images/bioenergetic vitalization/cell.jpg",
    name: "Bio Vitalization Cell",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/cell harmony.jpg",
    tags: [
      "cell",
      "cells",
      "bioenergetic vitalization",
      "bio",
      "bioenergetic",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic vitalization/epigenetic harmonization.jpg",
    name: "Epigenetic Harmonization",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/epigenetic harmonization.jpg",
    tags: [
      "epigenetic",
      "harmonization",
      "bioenergetic vitalization",
      "bio",
      "bioenergetic",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic vitalization/holistic support.jpg",
    name: "Holistic Support",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/holistic support.jpg",
    tags: [
      "holistic",
      "support",
      "bioenergetic vitalization",
      "bio",
      "bioenergetic",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic vitalization/nerves.jpg",
    name: "Bio Vitalization Nerve Harmony",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/nerve harmony.jpg",
    tags: [
      "nerves",
      "harmony",
      "bioenergetic vitalization",
      "bio",
      "bioenergetic",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic vitalization/pineal gland.jpg",
    name: "Pineal Gland Harmony",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/pineal gland harmony.jpg",
    tags: ["pineal", "gland", "bioenergetic vitalization"],
  },
  {
    img: "images/bioenergetic vitalization/regeneration 1.jpg",
    name: "Regeneration 1",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/regeneration 1.jpg",
    tags: [
      "regeneration",
      "bioenergetic vitalization",
      "bio",
      "bioenergetic",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic vitalization/regeneration 2.jpg",
    name: "Regeneration 2",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/regeneration 2.jpg",
    tags: [
      "regeneration",
      "bioenergetic vitalization",
      "bio",
      "bioenergetic",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic vitalization/regeneration 3.jpg",
    name: "Regeneration 3",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/regeneration 3.jpg",
    tags: [
      "regeneration",
      "bioenergetic vitalization",
      "bio",
      "bioenergetic",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic vitalization/stability.jpg",
    name: "Stability",
    models: ["pro"],
    modal: "images/modal content/bioenergetic vitalization modal/stability.jpg",
    tags: [
      "stability",
      "bioenergetic vitalization",
      "bio",
      "bioenergetic",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic vitalization/tissue.jpg",
    name: "Tissue Harmony",
    models: ["pro"],
    modal:
      "images/modal content/bioenergetic vitalization modal/tissue harmony.jpg",
    tags: [
      "tissue",
      "harmony",
      "bioenergetic vitalization",
      "bio",
      "bioenergetic",
      "inflammation",
    ],
  },
  {
    img: "images/bioenergetic vitalization/youth.jpg",
    name: "Youth",
    models: ["pro"],
    modal: "images/modal content/bioenergetic vitalization modal/youth.jpg",
    tags: ["youth", "bioenergetic vitalization"],
  },
  //BIOENERGETIC VITALIZATION
  //DEEP CYCLE H
  {
    img: "images/deep cycle H/breath of life.jpg",
    name: "Breath of Life",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/breath of life.jpg",
    tags: ["deep cycle H", "breath", "of", "life", "live", "asthma"],
  },
  {
    img: "images/deep cycle H/clean all.jpg",
    name: "Clean All",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/clean all.jpg",
    tags: [
      "deep cycle H",
      "clean",
      "all",
      "cleanse",
      "clear",
      "pure",
      "purify",
      "asthma",
      "cold",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  {
    img: "images/deep cycle H/digest all.jpg",
    name: "Digest All",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/digest all.jpg",
    tags: [
      "deep cycle H",
      "digest",
      "all",
      "digestion",
      "gut",
      "food",
      "eat",
      "eating",
      "gi",
      "gastrointestinal",
      "anxiety",
      "emotion",
      "emotions",
      "emotional",
      "candida",
      "yeast",
    ],
  },
  {
    img: "images/deep cycle H/energy work.jpg",
    name: "Energy Work",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/energy work.jpg",
    tags: [
      "deep cycle H",
      "energy",
      "energy cleanse",
      "work",
      "clear",
      "cleanse",
      "pure",
      "purify",
      "fortify",
      "strength",
      "strengthen",
    ],
  },
  {
    img: "images/deep cycle H/free flow.jpg",
    name: "Free Flow",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/free flow.jpg",
    tags: ["deep cycle H", "free", "flow", "move", "movement"],
  },
  {
    img: "images/deep cycle H/go to the roots.jpg",
    name: "Go To The Roots",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/go to the roots.jpg",
    tags: [
      "deep cycle H",
      "go",
      "to",
      "the",
      "roots",
      "root",
      "base",
      "foundation",
      "beginning",
      "asthma",
      "anxiety",
    ],
  },
  {
    img: "images/deep cycle H/kidney harmony female.jpg",
    name: "Kidney Harmony Female",
    models: ["all", "plus", "pro"],
    modal:
      "images/modal content/deep cycle H modal/kidney harmony female and male.jpg",
    tags: [
      "deep cycle H",
      "kidney",
      "harmony",
      "female",
      "feminine",
      "woman",
      "women",
      "organ",
      "organs",
    ],
  },
  {
    img: "images/deep cycle H/kidney harmony male.jpg",
    name: "Kidney Harmony Male",
    models: ["all", "plus", "pro"],
    modal:
      "images/modal content/deep cycle H modal/kidney harmony female and male.jpg",
    tags: [
      "deep cycle H",
      "kidney",
      "harmony",
      "male",
      "masculine",
      "man",
      "men",
      "organ",
      "organs",
    ],
  },
  {
    img: "images/deep cycle H/pure calm.jpg",
    name: "Pure Calm",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/pure calm.jpg",
    tags: [
      "deep cycle H",
      "pure",
      "calm",
      "relax",
      "relaxing",
      "relief",
      "reliving",
      "anxiety",
    ],
  },
  {
    img: "images/deep cycle H/pure energy.jpg",
    name: "Pure Energy",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/pure energy.jpg",
    tags: [
      "deep cycle H",
      "pure",
      "energy",
      "up",
      "lifting",
      "power",
      "strength",
      "strengthen",
    ],
  },
  {
    img: "images/deep cycle H/renewal.jpg",
    name: "Renewal",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/renewal.jpg",
    tags: [
      "deep cycle H",
      "renewal",
      "renew",
      "begin",
      "fresh",
      "refresh",
      "clean",
      "cleanse",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  {
    img: "images/deep cycle H/sensitive.jpg",
    name: "Sensitive",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/deep cycle H modal/sensitive.jpg",
    tags: [
      "deep cycle H",
      "sensitive",
      "sensitivity",
      "asthma",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  //DEEP CYCLE H
  //DIGITAL NUTRITION MIXTURES 1
  {
    img: "images/digital nutrition mixtures 1/brain.jpg",
    name: "Brain",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/brain harmony.jpg",
    tags: ["brain", "brain fog", "brainfog", "brain foggy", "brain foginess"],
  },
  {
    img: "images/digital nutrition mixtures 1/ears.jpg",
    name: "Ears",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 1 modal/ear harmony.jpg",
    tags: [
      "ears",
      "ear",
      "hearing",
      "listen",
      "listening",
      "listen",
      "listening",
      "hearing loss",
      "hearingloss",
      "deaf",
      "deafness",
      "deafening",
      "deafeningly",
      "deafeningness",
    ],
  },
  {
    img: "images/digital nutrition mixtures 1/gastrointestinal system.jpg",
    name: "Gastrointestinal System",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/gastrointestinal harmony.jpg",
    tags: [
      "gastrointestinal system",
      "gastrointestinal",
      "gastro",
      "gi",
      "digest",
      "digestion",
      "digestive",
      "digestive system",
      "candida",
      "yeast",
    ],
  },
  {
    img: "images/digital nutrition mixtures 1/hair.jpg",
    name: "Hair harmony",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/hair harmony.jpg",
    tags: ["hair", "hair loss", "hairloss"],
  },
  {
    img: "images/digital nutrition mixtures 1/head.jpg",
    name: "Head",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/head harmony.jpg",
    tags: [
      "head",
      "headache",
      "headaches",
      "migraine",
      "migraines",
      "migraine",
      "oral",
      "teeth",
    ],
  },
  {
    img: "images/digital nutrition mixtures 1/heart.jpg",
    name: "Heart",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/heart harmony.jpg",
    tags: [
      "heart",
      "cardiovascular",
      "cardiovascular system",
      "cardio",
      "cardiac",
      "cardiac system",
      "cardiac system",
    ],
  },
  {
    img: "images/digital nutrition mixtures 1/kidney.jpg",
    name: "Kidney",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/kidney harmony.jpg",
    tags: ["kidney", "kidneys", "renal", "renal syst"],
  },
  {
    img: "images/digital nutrition mixtures 1/muscles.jpg",
    name: "Muscles",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/muscle harmony.jpg",
    tags: ["muscles", "muscle", "muscular", "muscular system", "inflammation"],
  },
  {
    img: "images/digital nutrition mixtures 1/nails.jpg",
    name: "Nails",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/nail harmony.jpg",
    tags: ["nails", "nail", "nailbed", "nail bed", "nailbeds", "nail beds"],
  },
  {
    img: "images/digital nutrition mixtures 1/nerves.jpg",
    name: "Nerves",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/nerve harmony.jpg",
    tags: ["nerves", "nerve", "nervous", "nervous system", "inflammation"],
  },
  {
    img: "images/digital nutrition mixtures 1/skin.jpg",
    name: "Digital Nutrition Skin",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/skin harmony.jpg",
    tags: ["skin", "skin care", "skincare", "itching", "rash", "inflammation"],
  },
  {
    img: "images/digital nutrition mixtures 1/thyroid.jpg",
    name: "Thyroid",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 1 modal/thyroid harmony.jpg",
    tags: [
      "thyroid",
      "thyroid gland",
      "thyroid glands",
      "thyroidal",
      "thyroidals",
      "thyroidal gland",
      "thyroidal glands",
      "thyroidal system",
      "thyroidal systems",
      "thyroidal glandular",
      "thyroidal glandulars",
      "thyroidal glandular system",
    ],
  },
  //DIGITAL NUTRITION MIXTURES 1
  //DIGITAL NUTRITION MIXTURES 2
  {
    img: "images/digital nutrition mixtures 2/age.jpg",
    name: "Age",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 2 modal/age.jpg",
    tags: ["age", "aging", "ageless", "agelessness"],
  },
  {
    img: "images/digital nutrition mixtures 2/alkaline powder.jpg",
    name: "Alkaline Powder",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 2 modal/alkaline power.jpg",
    tags: ["alkaline", "powder", "alkaline powder"],
  },
  {
    img: "images/digital nutrition mixtures 2/amino acids.jpg",
    name: "Amino Acids",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 2 modal/amino acids.jpg",
    tags: ["amino acids", "amino acid", "amino", "acid", "acids"],
  },
  {
    img: "images/digital nutrition mixtures 2/blood.jpg",
    name: "Blood",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 2 modal/blood harmony.jpg",
    tags: ["blood", "bloodstream", "circulation", "blood circulation", "body"],
  },
  {
    img: "images/digital nutrition mixtures 2/connective tissue.jpg",
    name: "Connective Tissue",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 2 modal/connective tissue harmony.jpg",
    tags: [
      "connective tissue",
      "connective",
      "tissue",
      "connective tissues",
      "tissues",
      "inflammation",
    ],
  },
  {
    img: "images/digital nutrition mixtures 2/hypovitaminosis.jpg",
    name: "Hypovitaminosis",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 2 modal/vitamin intake.jpg",
    tags: ["vitamin", "vitamins", "nutrition", "hypovitaminosis"],
  },
  {
    img: "images/digital nutrition mixtures 2/liver.jpg",
    name: "Liver",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 2 modal/liver harmony.jpg",
    tags: [
      "liver",
      "liver cleanse",
      "liver cleanser",
      "liver cleansing",
      "liver detox",
      "liver detoxification",
      "liver detoxifier",
      "liver detoxifiers",
      "liver detoxify",
      "liver detoxifying",
      "liver detoxification",
    ],
  },
  {
    img: "images/digital nutrition mixtures 2/minerals.jpg",
    name: "Minerals",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 2 modal/minerals.jpg",
    tags: [
      "minerals",
      "mineral",
      "mineralization",
      "mineralize",
      "mineralizing",
    ],
  },
  {
    img: "images/digital nutrition mixtures 2/trace elements.jpg",
    name: "Trace Elements",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 2 modal/trace elements.jpg",
    tags: ["trace elements", "trace element", "trace", "elements"],
  },
  {
    img: "images/digital nutrition mixtures 2/vegan.jpg",
    name: "Vegan",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 2 modal/vegan.jpg",
    tags: ["vegan"],
  },
  {
    img: "images/digital nutrition mixtures 2/vitamin b complex.jpg",
    name: "Vitamin B Complex",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 2 modal/vitamin b complex.jpg",
    tags: ["vitamin b complex", "vitamin b", "vitamin", "vitamins"],
  },
  {
    img: "images/digital nutrition mixtures 2/weight.jpg",
    name: "Digital Nutrition Weight",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 2 modal/weight.jpg",
    tags: ["weight", "weight loss", "weightloss", "weight gain", "weightgain"],
  },
  //DIGITAL NUTRITION MIXTURES 2
  //DIGITAL NUTRITION MIXTURES 3
  {
    img: "images/digital nutrition mixtures 3/2ry plant substances.jpg",
    name: "2ry Plant Substances",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 3 modal/plant substances.jpg",
    tags: ["plant", "substances", "plant substances", "2ry plant substances"],
  },
  {
    img: "images/digital nutrition mixtures 3/alcohol intake.jpg",
    name: "Alcohol Intake",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 3 modal/alcohol intake.jpg",
    tags: ["alcohol", "intake", "alcohol intake"],
  },
  {
    img: "images/digital nutrition mixtures 3/allergies.jpg",
    name: "Allergies",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 3 modal/allergies.jpg",
    tags: [
      "allergies",
      "allergy",
      "allergic",
      "allergic reaction",
      "allergic reactions",
      "allergic responses",
      "allergic response",
      "allergic sensitivity",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  {
    img: "images/digital nutrition mixtures 3/antioxidant.jpg",
    name: "Antioxidant",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 3 modal/antioxidants.jpg",
    tags: ["antioxidant", "antioxidants"],
  },
  {
    img: "images/digital nutrition mixtures 3/fertility.jpg",
    name: "Fertility",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 3 modal/birth and fertility.jpg",
    tags: ["fertility", "fertile"],
  },
  {
    img: "images/digital nutrition mixtures 3/hormonal system.jpg",
    name: "Hormonal System",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 3 modal/hormonal system harmony.jpg",
    tags: [
      "hormonal system",
      "hormonal",
      "hormone",
      "hormones",
      "hormone system",
      "hormonal systems",
    ],
  },
  {
    img: "images/digital nutrition mixtures 3/immune system.jpg",
    name: "Immune System",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 3 modal/defence and immune system.jpg",
    tags: [
      "immune system",
      "immune",
      "immunity",
      "immunities",
      "immune systems",
    ],
  },
  {
    img: "images/digital nutrition mixtures 3/libido.jpg",
    name: "Libido",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 3 modal/libido.jpg",
    tags: ["libido"],
  },
  {
    img: "images/digital nutrition mixtures 3/lymphatic system.jpg",
    name: "Lymphatic System",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 3 modal/lymphatic system harmony.jpg",
    tags: [
      "lymphatic system",
      "lymphatic",
      "lymph",
      "lymph system",
      "lymph systems",
    ],
  },
  {
    img: "images/digital nutrition mixtures 3/menstruation.jpg",
    name: "Menstruation",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 3 modal/for women.jpg",
    tags: [
      "menstruation",
      "moon",
      "period",
      "menstrual",
      "menstrual cycle",
      "menstrual cycles",
      "menstrual period",
      "menstrual periods",
    ],
  },
  {
    img: "images/digital nutrition mixtures 3/spirituality.jpg",
    name: "Spirituality",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 3 modal/spirituality.jpg",
    tags: [
      "spirituality",
      "spiritual",
      "spirit",
      "spiritualism",
      "spiritualist",
      "spiritualists",
      "spiritualistic",
    ],
  },
  {
    img: "images/digital nutrition mixtures 3/toxins.jpg",
    name: "Toxins",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 3 modal/impurities and toxins.jpg",
    tags: [
      "toxins",
      "toxin",
      "toxic",
      "toxicity",
      "toxicities",
      "toxicity levels",
      "toxicity level",
      "toxic levels",
      "toxic level",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  //DIGITAL NUTRITION MIXTURES 3
  //DIGITAL NUTRITION MIXTURES 4
  {
    img: "images/digital nutrition mixtures 4/children.jpg",
    name: "Children",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/children.jpg",
    tags: [
      "children",
      "child",
      "kid",
      "kids",
      "baby",
      "babies",
      "infant",
      "infants",
      "toddler",
      "toddlers",
      "childhood",
      "childhood development",
    ],
  },
  {
    img: "images/digital nutrition mixtures 4/energy.jpg",
    name: "Energy",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/energy.jpg",
    tags: [
      "energy",
      "energetic",
      "energize",
      "energizing",
      "energized",
      "energization",
    ],
  },
  {
    img: "images/digital nutrition mixtures 4/eyesight.jpg",
    name: "Eyesight",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/eyesight.jpg",
    tags: ["eyesight", "eyes", "eye", "vision", "see", "seeing", "sight"],
  },
  {
    img: "images/digital nutrition mixtures 4/fatigue.jpg",
    name: "Fatigue",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/fatigue.jpg",
    tags: [
      "fatigue",
      "tired",
      "tiredness",
      "exhaustion",
      "exhausted",
      "exhaust",
      "exhausting",
    ],
  },
  {
    img: "images/digital nutrition mixtures 4/growth.jpg",
    name: "Growth",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/growth.jpg",
    tags: ["growth", "grow", "growing", "develop", "developing", "development"],
  },
  {
    img: "images/digital nutrition mixtures 4/men.jpg",
    name: "Men",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/men.jpg",
    tags: ["men", "masculine", "male"],
  },
  {
    img: "images/digital nutrition mixtures 4/psyche.jpg",
    name: "Psyche",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/psyche.jpg",
    tags: [
      "psyche",
      "psychic",
      "psychological",
      "psychologically",
      "psychology",
    ],
  },
  {
    img: "images/digital nutrition mixtures 4/regeneration.jpg",
    name: "Digital Nutrition Regeneration",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 4 modal/regeneration.jpg",
    tags: [
      "regeneration",
      "regenerate",
      "renew",
      "renewal",
      "renewing",
      "renewed",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  {
    img: "images/digital nutrition mixtures 4/sleep.jpg",
    name: "Sleep",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/sleep.jpg",
    tags: ["sleep", "sleeping", "sleepiness", "sleepy"],
  },
  {
    img: "images/digital nutrition mixtures 4/sports.jpg",
    name: "Sports",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/sports.jpg",
    tags: ["sports", "sport", "athletic", "athletics", "athlete"],
  },
  {
    img: "images/digital nutrition mixtures 4/women.jpg",
    name: "Women",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 4 modal/women.jpg",
    tags: ["women", "feminine", "female"],
  },
  {
    img: "images/digital nutrition mixtures 4/wounds.jpg",
    name: "Wounds",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 4 modal/skin and wounds.jpg",
    tags: ["wounds", "wound", "injury", "injuries", "itching", "rash"],
  },
  //DIGITAL NUTRITION MIXTURES 4
  //DIGITAL NUTRITION MIXTURES 5
  {
    img: "images/digital nutrition mixtures 5/activation.jpg",
    name: "Activation",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/activation.jpg",
    tags: ["activation", "activate", "activating", "activated"],
  },
  {
    img: "images/digital nutrition mixtures 5/breath.jpg",
    name: "Breath",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/breath.jpg",
    tags: ["breath", "breathe", "breathing", "breathwork", "breath work"],
  },
  {
    img: "images/digital nutrition mixtures 5/digital nutrition circulation.jpg",
    name: "Digital Nutrition Circulation",
    models: ["pro"],
    modal:
      "images/modal content/digital nutrition mix 5 modal/digital nutrition circulation.jpg",
    tags: [
      "circulation",
      "circulate",
      "flow",
      "circulating",
      "circulated",
      "blood",
      "blood circulation",
      "blood flow",
      "bloodstream",
      "blood stream",
      "circulatory system",
      "circulatory systems",
      "body",
    ],
  },
  {
    img: "images/digital nutrition mixtures 5/competition.jpg",
    name: "Competition",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/competition.jpg",
    tags: [
      "competition",
      "compete",
      "competing",
      "competitor",
      "competitors",
      "competitive",
      "competitiveness",
    ],
  },
  {
    img: "images/digital nutrition mixtures 5/energetic.jpg",
    name: "Energetic",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/energetic.jpg",
    tags: [
      "energetic",
      "energy",
      "energize",
      "energizing",
      "energized",
      "energization",
    ],
  },
  {
    img: "images/digital nutrition mixtures 5/exertion.jpg",
    name: "Exertion",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/exertion.jpg",
    tags: ["exertion", "exert", "exerting", "exerted", "exertive"],
  },
  {
    img: "images/digital nutrition mixtures 5/lifestyle.jpg",
    name: "Lifestyle",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/lifestyle.jpg",
    tags: ["lifestyle", "life", "style", "lifestyles"],
  },
  {
    img: "images/digital nutrition mixtures 5/mobility.jpg",
    name: "Mobility",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/mobility.jpg",
    tags: ["mobility", "mobile", "move", "moving", "movement", "movements"],
  },
  {
    img: "images/digital nutrition mixtures 5/motion.jpg",
    name: "Motion",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/motion.jpg",
    tags: ["motion", "move", "moving", "movement", "movements"],
  },
  {
    img: "images/digital nutrition mixtures 5/reduction.jpg",
    name: "Reduction",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/reduction.jpg",
    tags: ["reduction", "reduce", "reducing", "reduced"],
  },
  {
    img: "images/digital nutrition mixtures 5/rigidity.jpg",
    name: "Rigidity",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/rigidity.jpg",
    tags: ["rigidity", "rigid", "rigidness", "rigidly"],
  },
  {
    img: "images/digital nutrition mixtures 5/structure.jpg",
    name: "Structure",
    models: ["pro"],
    modal: "images/modal content/digital nutrition mix 5 modal/structure.jpg",
    tags: ["structure", "structures", "structural", "structurally"],
  },
  //DIGITAL NUTRITION MIXTURES 5
  //FITNESS
  {
    img: "images/fitness/fitness circulation.jpg",
    name: "Fitness Circulation",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/fitness modal/fitness circulation.jpg",
    tags: ["fitness", "circulation", "circulate", "flow", "fitness", "body"],
  },
  {
    img: "images/fitness/deep relaxation.jpg",
    name: "Deep Relaxation",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/fitness modal/deep relaxation.jpg",
    tags: [
      "fitness",
      "deep",
      "relaxation",
      "relax",
      "refresh",
      "calm",
      "peace",
      "fitness",
      "anxiety",
    ],
  },
  {
    img: "images/fitness/muscle harmony.jpg",
    name: "Muscle Harmony",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/fitness modal/muscle harmony.jpg",
    tags: [
      "fitness",
      "muscle",
      "harmony",
      "muscles",
      "fitness",
      "exercise",
      "work",
      "out",
      "fitness",
      "inflammation",
    ],
  },
  {
    img: "images/fitness/performance.jpg",
    name: "Performance",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/fitness modal/perfomance.jpg",
    tags: [
      "fitness",
      "performance",
      "perform",
      "optimal",
      "potential",
      "aptitude",
      "result",
      "results",
      "fitness",
    ],
  },
  {
    img: "images/fitness/regeneration.jpg",
    name: "Fitness Regeneration",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/fitness modal/regeneration.jpg",
    tags: [
      "fitness",
      "regeneration",
      "regenerate",
      "renew",
      "fresh",
      "refresh",
      "align",
      "alignment",
      "cleanse",
      "clear",
      "fitness",
    ],
  },
  {
    img: "images/fitness/stamina.jpg",
    name: "Stamina",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/fitness modal/stamina.jpg",
    tags: [
      "fitness",
      "stamina",
      "endurance",
      "out",
      "last",
      "fortify",
      "fitness",
    ],
  },
  {
    img: "images/fitness/strength.jpg",
    name: "Strength",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/fitness modal/strength.jpg",
    tags: ["fitness", "strength", "strengthen", "power", "force", "fitness"],
  },
  {
    img: "images/fitness/weight.jpg",
    name: "Fitness Weight",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/fitness modal/weight.jpg",
    tags: [
      "fitness",
      "weight",
      "gain",
      "loss",
      "fat",
      "muscle",
      "muscles",
      "fitness",
    ],
  },
  //FITNESS
  //GOLD CYCLE
  {
    img: "images/gold cycle/balance.jpg",
    name: "Balance",
    models: ["all", "gold", "holistic", "plus", "pro"],
    modal: "images/modal content/gold modal/gold balance modal.jpg",
    tags: [
      "gold cycle",
      "gold",
      "cycle",
      "balance",
      "stability",
      "stable",
      "center",
      "equal",
      "equilibrium",
      "asthma",
      "anxiety",
    ],
  },
  {
    img: "images/gold cycle/being.jpg",
    name: "being",
    models: ["all", "gold", "holistic", "plus", "pro"],
    modal: "images/modal content/gold modal/gold being modal.jpg",
    tags: [
      "gold cycle",
      "gold",
      "cycle",
      "being",
      "now",
      "moment",
      "calm",
      "peace",
      "center",
      "align",
      "alignment",
      "anxiety",
    ],
  },
  {
    img: "images/gold cycle/care.jpg",
    name: "care",
    models: ["all", "gold", "holistic", "plus", "pro"],
    modal: "images/modal content/gold modal/gold care modal.jpg",
    tags: [
      "gold cycle",
      "gold",
      "cycle",
      "care",
      "self care",
      "love",
      "caring",
      "connecting",
      "connection",
      "nurture",
      "nurturing",
      "asthma",
      "anxiety",
    ],
  },
  {
    img: "images/gold cycle/energy.jpg",
    name: "energy",
    models: ["all", "gold", "holistic", "plus", "pro"],
    modal: "images/modal content/gold modal/gold energy modal.jpg",
    tags: [
      "gold cycle",
      "gold",
      "cycle",
      "energy",
      "pure",
      "up",
      "lifting",
      "power",
      "strength",
      "strengthen",
      "anxiety",
    ],
  },
  {
    img: "images/gold cycle/pure.jpg",
    name: "pure",
    models: ["all", "gold", "holistic", "plus", "pro"],
    modal: "images/modal content/gold modal/gold pure modal.jpg",
    tags: [
      "gold cycle",
      "gold",
      "cycle",
      "pure",
      "impurities",
      "purify",
      "clean",
      "clear",
      "cleanse",
      "remove",
      "asthma",
      "anxiety",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  {
    img: "images/gold cycle/relax.jpg",
    name: "relax",
    models: ["all", "gold", "holistic", "plus", "pro"],
    modal: "images/modal content/gold modal/gold relax modal.jpg",
    tags: [
      "gold cycle",
      "gold",
      "cycle",
      "relax",
      "relaxing",
      "relaxation",
      "refresh",
      "calm",
      "peace",
      "anxiety",
    ],
  },
  {
    img: "images/gold cycle/release.jpg",
    name: "release",
    models: ["all", "gold", "holistic", "plus", "pro"],
    modal: "images/modal content/gold modal/gold release modal.jpg",
    tags: [
      "gold cycle",
      "gold",
      "cycle",
      "release",
      "let",
      "go",
      "clean",
      "cleanse",
      "pure",
      "purify",
      "asthma",
      "cramps",
      "anxiety",
      "inflammation",
    ],
  },
  //FITNESS
  //JOB AND SLEEP
  {
    img: "images/job and sleep/activation.jpg",
    name: "activation",
    models: ["pro"],
    modal: "images/modal content/job modal/activation.jpg",
    tags: [
      "job and sleep",
      "sleep",
      "job",
      "activation",
      "activate",
      "activating",
    ],
  },
  {
    img: "images/job and sleep/balance nerves.jpg",
    name: "balance nerves",
    models: ["pro"],
    modal: "images/modal content/job modal/balance sleep.jpg",
    tags: [
      "job and sleep",
      "sleep",
      "job",
      "balance",
      "nerves",
      "nerve",
      "nervous",
      "nervousness",
      "nervous systems",
    ],
  },
  {
    img: "images/job and sleep/balanced sleep.jpg",
    name: "balanced sleep",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/sleep modal/balanced sleep.jpg",
    tags: [
      "job and sleep",
      "job",
      "balanced",
      "sleep",
      "rest",
      "deep",
      "equal",
      "equilibrium",
      "rejuvenate",
    ],
  },
  {
    img: "images/job and sleep/bed rest.jpg",
    name: "bed rest",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/sleep modal/bed rest.jpg",
    tags: [
      "job and sleep",
      "job",
      "bed",
      "rest",
      "sleep",
      "rest",
      "deep",
      "rejuvenate",
    ],
  },
  {
    img: "images/job and sleep/exhaustion acute.jpg",
    name: "exhaustion acute",
    models: ["pro"],
    modal: "images/modal content/job modal/exhaustion acute.jpg",
    tags: [
      "exhaustion",
      "acute",
      "job and sleep",
      "job",
      "sleep",
      "exhaust",
      "exhausted",
      "exhausting",
      "exhaustion",
      "exhaustive",
      "acute exhaustion",
    ],
  },
  {
    img: "images/job and sleep/exhaustion system.jpg",
    name: "exhaustion systemic",
    models: ["pro"],
    modal: "images/modal content/job modal/exhaustion system.jpg",
    tags: [
      "exhaustion",
      "systemic",
      "job and sleep",
      "job",
      "sleep",
      "exhaust",
      "exhausted",
      "exhausting",
      "exhaustion",
      "exhaustive",
      "systemic exhaustion",
    ],
  },
  {
    img: "images/job and sleep/extreme stress.jpg",
    name: "extreme stress",
    models: ["pro"],
    modal: "images/modal content/job modal/extreme tension.jpg",
    tags: [
      "extreme",
      "stress",
      "stressful",
      "job and sleep",
      "job",
      "sleep",
      "extreme stress",
      "extremely stressful",
      "extremely stressed",
    ],
  },
  {
    img: "images/job and sleep/fatigue.jpg",
    name: "fatigue",
    models: ["pro"],
    modal: "images/modal content/job modal/fatigue.jpg",
    tags: [
      "fatigue",
      "tired",
      "tiredness",
      "exhaustion",
      "exhausted",
      "exhaust",
      "exhausting",
      "job and sleep",
      "job",
      "sleep",
      "fatigue",
      "fatigued",
    ],
  },
  {
    img: "images/job and sleep/fine flow.jpg",
    name: "fine flow",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/sleep modal/fine flow.jpg",
    tags: [
      "job and sleep",
      "job",
      "sleep",
      "fine",
      "flow",
      "aptitude",
      "performance",
      "refined",
      "optimal",
    ],
  },
  {
    img: "images/job and sleep/positive thoughts.jpg",
    name: "positive thoughts",
    models: ["pro"],
    modal: "images/modal content/job modal/positive thoughts.jpg",
    tags: [
      "positive",
      "thoughts",
      "job and sleep",
      "job",
      "sleep",
      "positive thoughts",
      "positivity",
      "positive thinking",
    ],
  },
  {
    img: "images/job and sleep/sleep syst.jpg",
    name: "sleep systemic",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/sleep modal/sleep system.jpg",
    tags: [
      "job and sleep",
      "job",
      "sleep",
      "systemic",
      "deep",
      "rest",
      "rejuvenate",
    ],
  },
  //JOB AND SLEEP
  //LEARNING
  {
    img: "images/learning/concentration acute.jpg",
    name: "concentration acute",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/learning modal/concentration acute.jpg",
    tags: ["learning", "concentration", "acute", "focus"],
  },
  {
    img: "images/learning/concentration syst.jpg",
    name: "concentration systemic",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/learning modal/concentration system.jpg",
    tags: ["learning", "concentration", "systemic", "focus"],
  },
  {
    img: "images/learning/exam acute.jpg",
    name: "exam acute",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/learning modal/exam acute.jpg",
    tags: ["exam", "acute", "focus", "learn", "learning", "performance"],
  },
  {
    img: "images/learning/exam syst.jpg",
    name: "exam systemic",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/learning modal/exam system.jpg",
    tags: ["exam", "systemic", "focus", "learn", "learning", "performance"],
  },
  {
    img: "images/learning/learning acute.jpg",
    name: "learning acute",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/learning modal/learning acute.jpg",
    tags: [
      "learning",
      "acute",
      "focus",
      "learn",
      "learning",
      "performance",
      "concentration",
    ],
  },
  {
    img: "images/learning/learning syst.jpg",
    name: "learning systemic",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/learning modal/learning system.jpg",
    tags: [
      "learning",
      "systemic",
      "focus",
      "learn",
      "learning",
      "performance",
      "concentration",
    ],
  },
  {
    img: "images/learning/memory.jpg",
    name: "memory",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/learning modal/memory.jpg",
    tags: [
      "learning",
      "memory",
      "remember",
      "retain",
      "retention",
      "recall",
      "focus",
    ],
  },
  {
    img: "images/learning/stress acute.jpg",
    name: "stress acute",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/learning modal/stress acute.jpg",
    tags: [
      "learning",
      "stress",
      "acute",
      "stressful",
      "relive",
      "reliving",
      "relax",
      "relaxing",
      "calm",
      "calming",
      "anxiety",
    ],
  },
  {
    img: "images/learning/stress syst.jpg",
    name: "stress systemic",
    models: ["all", "plus", "pro"],
    modal: "images/modal content/learning modal/stress system.jpg",
    tags: [
      "learning",
      "stress",
      "systemic",
      "stressful",
      "relive",
      "reliving",
      "relax",
      "relaxing",
      "calm",
      "calming",
      "anxiety",
    ],
  },
  //LEARNING
  //MENTAL BALANCE
  {
    img: "images/mental balance/contentment acute.jpg",
    name: "contentment acute",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/mental balance modal/contentment acute.jpg",
    tags: [
      "mental balance",
      "contentment",
      "acute",
      "peace",
      "calm",
      "relax",
      "relaxing",
      "balance",
      "anxiety",
      "mind",
    ],
  },
  {
    img: "images/mental balance/contentment syst.jpg",
    name: "contentment systemic",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/mental balance modal/contentment system.jpg",
    tags: [
      "mental balance",
      "contentment",
      "systemic",
      "peace",
      "calm",
      "relax",
      "relaxing",
      "balance",
      "anxiety",
      "mind",
    ],
  },
  {
    img: "images/mental balance/emotional wellbeing.jpg",
    name: "emotional wellbeing",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/mental balance modal/emotional wellbeing.jpg",
    tags: [
      "mental balance",
      "emotional",
      "wellbeing",
      "peace",
      "calm",
      "ease",
      "relax",
      "relaxing",
      "anxiety",
      "mind",
      "anger",
      "angry",
      "irritability",
      "irritable",
      "fear",
      "resentment",
      "resent",
    ],
  },
  {
    img: "images/mental balance/feel good syst.jpg",
    name: "feel good systemic",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/mental balance modal/feel good system.jpg",
    tags: [
      "mental balance",
      "feel",
      "good",
      "systemic",
      "peace",
      "calm",
      "enjoy",
      "enjoyment",
      "mind",
    ],
  },
  {
    img: "images/mental balance/inner strength syst.jpg",
    name: "inner strength systemic",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal:
      "images/modal content/mental balance modal/inner strength system.jpg",
    tags: [
      "mental balance",
      "inner",
      "strength",
      "systemic",
      "strengthen",
      "fortify",
      "perseverance",
      "anxiety",
      "confidence",
      "mind",
    ],
  },
  {
    img: "images/mental balance/inner unity.jpg",
    name: "inner unity",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/mental balance modal/inner unity.jpg",
    tags: [
      "mental balance",
      "inner",
      "unity",
      "oneness",
      "connection",
      "connecting",
      "center",
      "balance",
      "anxiety",
      "confidence",
      "mind",
    ],
  },
  {
    img: "images/mental balance/mental balance acute.jpg",
    name: "mental balance acute",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/mental balance modal/mental balance acute.jpg",
    tags: [
      "mental balance",
      "mental",
      "balance",
      "acute",
      "mind",
      "brain",
      "fog",
      "focus",
      "center",
      "equal",
      "equilibrium",
      "mind",
    ],
  },
  {
    img: "images/mental balance/wellbeing soul.jpg",
    name: "wellbeing soul",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/mental balance modal/wellbeing soul.jpg",
    tags: [
      "mental balance",
      "wellbeing",
      "soul",
      "peace",
      "calm",
      "care",
      "self care",
      "love",
      "relax",
      "relaxing",
      "anxiety",
      "mind",
    ],
  },
  //MENTAL BALANCE
  //MERIDIANS 1
  {
    img: "images/meridians 1/allergy meridian.jpg",
    name: "allergy meridian",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/allergy meridian.jpg",
    tags: [
      "allergy",
      "meridian",
      "meridians",
      "allergic",
      "clear",
      "cleanse",
      "asthma",
    ],
  },
  {
    img: "images/meridians 1/bladder.jpg",
    name: "bladder",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/bladder.jpg",
    tags: [
      "bladder",
      "urine",
      "urinate",
      "organ",
      "organs",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/connective tissue.jpg",
    name: "connective tissue",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/connective tissue.jpg",
    tags: [
      "connective",
      "tissue",
      "body",
      "movement",
      "move",
      "flexible",
      "flexibility",
      "meridian",
      "meridians",
      "inflammation",
    ],
  },
  {
    img: "images/meridians 1/fatty degeneration.jpg",
    name: "fatty degeneration",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/fatty degeneration.jpg",
    tags: [
      "fatty",
      "degeneration",
      "degenerate",
      "break",
      "down",
      "eliminate",
      "weight",
      "loss",
      "tone",
      "refine",
      "slim",
      "fit",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/gall bladder.jpg",
    name: "gall bladder",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/gallbladder.jpg",
    tags: [
      "gallbladder",
      "gall",
      "bladder",
      "liver",
      "digestion",
      "digest",
      "organ",
      "organs",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/heart.jpg",
    name: "heart",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/heart.jpg",
    tags: [
      "heart",
      "blood",
      "circulate",
      "circulation",
      "organ",
      "organs",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/joints.jpg",
    name: "joints",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/joints.jpg",
    tags: [
      "joints",
      "flexible",
      "flexibility",
      "stiff",
      "sore",
      "arthritis",
      "meridian",
      "meridians",
      "body",
    ],
  },
  {
    img: "images/meridians 1/large intestine.jpg",
    name: "large intestine",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/large intestine.jpg",
    tags: [
      "meridian",
      "meridians",
      "large",
      "intestine",
      "gut",
      "gi",
      "digest",
      "digestion",
      "organ",
      "organs",
      "asthma",
      "candida",
      "yeast",
    ],
  },
  {
    img: "images/meridians 1/skin harmony.jpg",
    name: "skin harmony",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/skin harmony.jpg",
    tags: [
      "meridian",
      "meridians",
      "skin",
      "harmony",
      "organ",
      "organs",
      "itching",
      "rash",
      "inflammation",
    ],
  },
  {
    img: "images/meridians 1/small intestine.jpg",
    name: "small intestine",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 1 modal/small intestine.jpg",
    tags: [
      "meridian",
      "meridians",
      "small",
      "intestine",
      "gut",
      "gi",
      "digest",
      "digestion",
      "organ",
      "organs",
    ],
  },
  //MERIDIANS 1
  //MERIDIANS 2
  {
    img: "images/meridians 2/meridian circulation.jpg",
    name: "Meridian circulation",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/meridian circulation.jpg",
    tags: [
      "meridian",
      "meridians",
      "circulation",
      "blood",
      "circulate",
      "flow",
      "body",
    ],
  },
  {
    img: "images/meridians 2/hormonal balance.jpg",
    name: "hormonal balance",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/hormonal balance.jpg",
    tags: ["meridian", "meridians", "hormonal", "hormone", "balance"],
  },
  {
    img: "images/meridians 2/kidney.jpg",
    name: "kidney",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/kidney.jpg",
    tags: ["meridian", "meridians", "kidney", "organ", "organs"],
  },
  {
    img: "images/meridians 2/liver.jpg",
    name: "liver",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/liver.jpg",
    tags: ["meridian", "meridians", "liver", "organ", "organs"],
  },
  {
    img: "images/meridians 2/lungs.jpg",
    name: "lungs",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/lungs.jpg",
    tags: ["meridian", "meridians", "lungs", "organ", "organs", "asthma"],
  },
  {
    img: "images/meridians 2/lymphatic system.jpg",
    name: "lymphatic system",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/lymphatic system.jpg",
    tags: ["meridian", "meridians", "lymphatic", "system"],
  },
  {
    img: "images/meridians 2/nerve meridian.jpg",
    name: "nerve meridian",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/nerve meridian.jpg",
    tags: ["meridian", "meridians", "nerve"],
  },
  {
    img: "images/meridians 2/organ meridian.jpg",
    name: "organ meridian",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/organ meridian.jpg",
    tags: ["meridian", "meridians", "organ", "organs"],
  },
  {
    img: "images/meridians 2/spleen-pancreas.jpg",
    name: "spleen-pancreas",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/spleen and pancreas.jpg",
    tags: ["meridian", "meridians", "spleen", "pancreas", "organ", "organs"],
  },
  {
    img: "images/meridians 2/stomach.jpg",
    name: "stomach",
    models: ["all", "holistic", "resonance", "plus", "pro"],
    modal: "images/modal content/meridians 2 modal/stomach.jpg",
    tags: ["meridian", "meridians", "stomach", "organ", "organs"],
  },
  //MERIDIANS 2
  //PAIN STIM
  {
    img: "images/pain stim/III.jpg",
    name: "III",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/pain stim modal/anxiety VIII.jpg",
    tags: [
      "pain",
      "painful",
      "anxiety",
      "hurt",
      "injury",
      "stimulation",
      "III",
    ],
  },
  {
    img: "images/pain stim/IV.jpg",
    name: "IV",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/pain stim modal/joints local IV.jpg",
    tags: [
      "pain",
      "painful",
      "hurt",
      "injury",
      "stimulation",
      "joint",
      "joint pain",
      "joints",
      "IV",
    ],
  },
  {
    img: "images/pain stim/pain locally.jpg",
    name: "pain locally",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/pain stim modal/chronic back pain II.jpg",
    tags: [
      "pain",
      "painful",
      "hurt",
      "injury",
      "stimulation",
      "locally",
      "local",
      "local pain",
      "cramps",
      "back",
      "back pain",
      "chronic",
      "chronic pain",
      "chronic back pain",
    ],
  },
  {
    img: "images/pain stim/pain.jpg",
    name: "pain",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/pain stim modal/chronic pain I.jpg",
    tags: [
      "pain",
      "painful",
      "hurt",
      "injury",
      "stimulation",
      "chronic",
      "chronic pain",
    ],
  },
  {
    img: "images/pain stim/V.jpg",
    name: "V",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/pain stim modal/migrane V.jpg",
    tags: [
      "pain",
      "painful",
      "hurt",
      "injury",
      "stimulation",
      "migraine",
      "head",
      "headache",
      "V",
    ],
  },
  {
    img: "images/pain stim/VI.jpg",
    name: "VI",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/pain stim modal/insomnia VI.jpg",
    tags: [
      "pain",
      "painful",
      "hurt",
      "injury",
      "stimulation",
      "insomnia",
      "sleep",
      "sleeping",
      "VI",
    ],
  },
  {
    img: "images/pain stim/VII.jpg",
    name: "VII",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/pain stim modal/depression VII.jpg",
    tags: [
      "pain",
      "painful",
      "hurt",
      "injury",
      "stimulation",
      "depression",
      "sad",
      "sadness",
      "VII",
    ],
  },
  {
    img: "images/pain stim/VIII.jpg",
    name: "VIII",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/pain stim modal/anxiety VIII.jpg",
    tags: [
      "pain",
      "painful",
      "hurt",
      "injury",
      "stimulation",
      "anxiety",
      "VIII",
    ],
  },
  //PAIN STIM
  //THE POWER OF THREE
  {
    img: "images/the power of three/conflict balance.jpg",
    name: "conflict balance",
    models: ["all", "resonance", "plus", "pro"],
    modal:
      "images/modal content/power of three bio bal modal/conflict balance.jpg",
    tags: ["the", "power", "of", "three", "conflict", "balance"],
  },
  {
    img: "images/the power of three/defense support.jpg",
    name: "defense support",
    models: ["all", "resonance", "plus", "pro"],
    modal:
      "images/modal content/power of three bio bal modal/defence support.jpg",
    tags: ["the", "power", "of", "three", "defense", "support"],
  },
  {
    img: "images/the power of three/friendly flora.jpg",
    name: "friendly flora",
    models: ["all", "resonance", "plus", "pro"],
    modal:
      "images/modal content/power of three bio bal modal/friendly flora.jpg",
    tags: ["the", "power", "of", "three", "friendly", "flora"],
  },
  {
    img: "images/the power of three/kapha.jpg",
    name: "kapha",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/power of three digital modal/kapha.jpg",
    tags: ["the", "power", "of", "three", "kapha"],
  },
  {
    img: "images/the power of three/pita.jpg",
    name: "pita",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/power of three digital modal/pita.jpg",
    tags: ["the", "power", "of", "three", "pita"],
  },
  {
    img: "images/the power of three/rebalance.jpg",
    name: "rebalance",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/power of three digital modal/vata.jpg",
    tags: ["the", "power", "of", "three", "rebalance", "asthma"],
  },
  {
    img: "images/the power of three/rife energetic.jpg",
    name: "rife energetic",
    models: ["all", "resonance", "plus", "pro"],
    modal:
      "images/modal content/power of three universal modal/classical energetic.jpg",
    tags: ["the", "power", "of", "three", "rife", "energetic"],
  },
  {
    img: "images/the power of three/rife physical.jpg",
    name: "rife physical",
    models: ["all", "resonance", "plus", "pro"],
    modal:
      "images/modal content/power of three universal modal/classical physical.jpg",
    tags: ["the", "power", "of", "three", "rife", "physical", "asthma"],
  },
  {
    img: "images/the power of three/vata.jpg",
    name: "vata",
    models: ["all", "resonance", "plus", "pro"],
    modal: "images/modal content/power of three digital modal/vata.jpg",
    tags: ["the", "power", "of", "three", "vata", "asthma"],
  },
  {
    img: "images/the power of three/zapper protocol.jpg",
    name: "zapper protocol",
    models: ["all", "resonance", "plus", "pro"],
    modal:
      "images/modal content/power of three universal modal/zapper protocol.jpg",
    tags: [
      "the",
      "power",
      "of",
      "three",
      "zapper",
      "protocol",
      "parasite",
      "parasite cleanse",
      "cold",
    ],
  },
];
