export const dataObjects = [
  //CHAKRAS
  {
    img: "images/chakras/crown.jpg",
    name: "crown chakra",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "crown",
      "head",
      "mind",
      "focus",
      "consciousness",
      "celestial",
      "spirit",
      "chakra",
    ],
  },
  {
    img: "images/chakras/Third eye.jpg",
    name: "third eye chakra",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "third",
      "eye",
      "intuition",
      "thought",
      "vision",
      "clarity",
      "insight",
      "focus",
      "dream",
      "chakra",
    ],
  },
  {
    img: "images/chakras/Throat.jpg",
    name: "throat chakra",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "throat",
      "voice",
      "truth",
      "confidence",
      "communication",
      "affirmation",
      "chakra",
    ],
  },
  {
    img: "images/chakras/heart.jpg",
    name: "heart chakra",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["heart", "love", "care", "compassion", "relation", "self", "chakra"],
  },
  {
    img: "images/chakras/solar.jpg",
    name: "solar plexus chakra",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "solar",
      "plexus",
      "power",
      "will",
      "strength",
      "strengthen",
      "manifest",
      "confidence",
      "perseverance",
      "determination",
      "chakra",
    ],
  },
  {
    img: "images/chakras/sacral.jpg",
    name: "sacral chakra",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "sacral",
      "creativity",
      "connection",
      "connecting",
      "relation",
      "sexuality",
      "creation",
      "chakra",
    ],
  },
  {
    img: "images/chakras/root.jpg",
    name: "root chakra",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "root",
      "survival",
      "safety",
      "ground",
      "protection",
      "persistance",
      "chakra",
    ],
  },
  //CHAKRAS
  //SKIN AND BEAUTY
  {
    img: "images/beauty and skin/scar harmony local.jpg",
    name: "scar harmony local",
    models: ["all", "resonance-plus", "pro"],
    tags: ["scar", "skin", "beauty", "local", "harmony"],
  },
  {
    img: "images/beauty and skin/scar harmony syst.jpg",
    name: "scar harmony systemic",
    models: ["all", "resonance-plus", "pro"],
    tags: ["scar", "skin", "beauty", "systemic", "harmony"],
  },
  {
    img: "images/beauty and skin/skin harmony local.jpg",
    name: "skin harmony local",
    models: ["all", "resonance-plus", "pro"],
    tags: ["skin", "beauty", "local", "harmony"],
  },
  {
    img: "images/beauty and skin/skin harmony syst.jpg",
    name: "skin harmony systemic",
    models: ["all", "resonance-plus", "pro"],
    tags: ["skin", "harmony", "beauty", "systemic"],
  },
  {
    img: "images/beauty and skin/skin impurity syst.jpg",
    name: "skin impurity systemic",
    models: ["all", "resonance-plus", "pro"],
    tags: ["skin", "impurity", "beauty", "systemic", "purity"],
  },
  //SKIN AND BEAUTY
  //BIOENERGETIC 1
  {
    img: "images/bioenergetic harmony 1/circulation.jpg",
    name: "circulation",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["blood", "circulation"],
  },
  {
    img: "images/bioenergetic harmony 1/defense.jpg",
    name: "defense",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["defense", "shield", "resistance", "immunity"],
  },
  {
    img: "images/bioenergetic harmony 1/eyes harmony.jpg",
    name: "eyes harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["eyes", "sight", "vision", "see", "look", "harmony"],
  },
  {
    img: "images/bioenergetic harmony 1/flexibility.jpg",
    name: "flexibility",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["flexibility", "flexible", "stretch", "move"],
  },
  {
    img: "images/bioenergetic harmony 1/for mature women.jpg",
    name: "for mature women",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: [
      "female",
      "feminine",
      "for",
      "mature",
      "women",
      "woman",
      "lady",
      "ladies",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/for women.jpg",
    name: "for women",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["female", "feminine", "for", "women", "woman", "lady", "ladies"],
  },
  {
    img: "images/bioenergetic harmony 1/hormone harmony.jpg",
    name: "hormone harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["hormone", "harmony"],
  },
  {
    img: "images/bioenergetic harmony 1/intestine harmony.jpg",
    name: "intestine harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: [
      "intestine",
      "harmony",
      "gut",
      "gastrointestinal",
      "gi",
      "digest",
      "digestion",
    ],
  },
  {
    img: "images/bioenergetic harmony 1/nerve harmony.jpg",
    name: "nerve harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["nerve", "harmony"],
  },
  {
    img: "images/bioenergetic harmony 1/potency.jpg",
    name: "potency",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["potency", "potent"],
  },
  {
    img: "images/bioenergetic harmony 1/sensitivity.jpg",
    name: "sensitivity",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["sensitivity", "sensitive"],
  },
  {
    img: "images/bioenergetic harmony 1/shiver.jpg",
    name: "shiver",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["shiver", "cold", "chill"],
  },
  //BIOENERGETIC 1
  //BIOENERGETIC 2
  {
    img: "images/bioenergetic harmony 2/bacteria harmony.jpg",
    name: "bacteria harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["bacteria", "harmony", "gut"],
  },
  {
    img: "images/bioenergetic harmony 2/food imbalance.jpg",
    name: "food imbalance",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["food", "imbalance", "digestion"],
  },
  {
    img: "images/bioenergetic harmony 2/gastrointestinal harmony.jpg",
    name: "gastrointestinal harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["gastrointestinal", "harmony", "gut", "digestion", "digest"],
  },
  {
    img: "images/bioenergetic harmony 2/head harmony.jpg",
    name: "head harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: [
      "head",
      "harmony",
      "headache",
      "brain",
      "mind",
      "fog",
      "clarity",
      "focus",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/impurities.jpg",
    name: "impurities",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: [
      "impurities",
      "pure",
      "purify",
      "clean",
      "clear",
      "cleanse",
      "remove",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/joints-bone harmony.jpg",
    name: "joints-bone harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: [
      "joints",
      "bone",
      "harmony",
      "skeletal",
      "structure",
      "frame",
      "foundation",
      "flexibility",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/liver harmony.jpg",
    name: "liver harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: [
      "liver",
      "harmony",
      "cleanse",
      "clean",
      "fortify",
      "renew",
      "detox",
      "organ",
      "organs",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/lung harmony.jpg",
    name: "lung harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: [
      "lung",
      "harmony",
      "cleanse",
      "clean",
      "fortify",
      "renew",
      "detox",
      "breath",
      "breathing",
    ],
  },
  {
    img: "images/bioenergetic harmony 2/prostate harmony.jpg",
    name: "prostate harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["prostate", "harmony", "fortify", "renew", "organ", "organs"],
  },
  {
    img: "images/bioenergetic harmony 2/sciatica nerve harmony local.jpg",
    name: "sciatica nerve harmony local",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["sciatica", "nerve", "harmony", "local"],
  },
  {
    img: "images/bioenergetic harmony 2/thyroid gland harmony.jpg",
    name: "thyroid gland harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["thyroid", "gland", "harmony"],
  },
  {
    img: "images/bioenergetic harmony 2/tonsil harmony.jpg",
    name: "tonsil harmony",
    models: ["all", "holistic", "resonance-plus", "pro"],
    tags: ["tonsil", "harmony", "mouth", "throat"],
  },
  //BIOENERGETIC 2
  //BIOENERGETIC SUPPORT
  {
    img: "images/bioenergetic support/bioenergetic boost.jpg",
    name: "bioenergetic boost",
    models: ["all", "gold", "resonance-plus", "pro"],
    tags: ["bioenergetic", "boost"],
  },
  {
    img: "images/bioenergetic support/coherence.jpg",
    name: "coherence",
    models: ["all", "gold", "resonance-plus", "pro"],
    tags: ["coherence", "mind", "brain", "focus", "learn", "learning"],
  },
  //BIOENERGETIC SUPPORT
  //DEEP CYCLE H
  {
    img: "images/deep cycle H/breath of life.jpg",
    name: "breath of life",
    models: ["all", "resonance-plus", "pro"],
    tags: ["breath", "of", "life", "live"],
  },
  {
    img: "images/deep cycle H/clean all.jpg",
    name: "clean all",
    models: ["all", "resonance-plus", "pro"],
    tags: ["clean", "all", "cleanse", "clear", "pure", "purify"],
  },
  {
    img: "images/deep cycle H/digest all.jpg",
    name: "digest all",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "digest",
      "all",
      "digestion",
      "gut",
      "food",
      "eat",
      "eating",
      "gi",
      "gastrointestinal",
    ],
  },
  {
    img: "images/deep cycle H/energy work.jpg",
    name: "energy work",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "energy",
      "energy cleanse",
      "work",
      "clear",
      "cleanse",
      "pure",
      "purify",
      "fortify",
      "strength",
      "strengthen",
    ],
  },
  {
    img: "images/deep cycle H/free flow.jpg",
    name: "free flow",
    models: ["all", "resonance-plus", "pro"],
    tags: ["free", "flow", "move", "movement"],
  },
  {
    img: "images/deep cycle H/go to the roots.jpg",
    name: "go to the roots",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "go",
      "to",
      "the",
      "roots",
      "root",
      "base",
      "foundation",
      "beginning",
    ],
  },
  {
    img: "images/deep cycle H/kidney harmony female.jpg",
    name: "kidney harmony female",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "kidney",
      "harmony",
      "female",
      "feminine",
      "woman",
      "women",
      "organ",
      "organs",
    ],
  },
  {
    img: "images/deep cycle H/kidney harmony male.jpg",
    name: "kidney harmony male",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "kidney",
      "harmony",
      "male",
      "masculine",
      "man",
      "men",
      "organ",
      "organs",
    ],
  },
  {
    img: "images/deep cycle H/pure calm.jpg",
    name: "pure calm",
    models: ["all", "resonance-plus", "pro"],
    tags: ["pure", "calm", "relax", "relaxing", "relief", "reliving"],
  },
  {
    img: "images/deep cycle H/pure energy.jpg",
    name: "pure energy",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "pure",
      "energy",
      "up",
      "lifting",
      "power",
      "strength",
      "strengthen",
    ],
  },
  {
    img: "images/deep cycle H/renewal.jpg",
    name: "renewal",
    models: ["all", "resonance-plus", "pro"],
    tags: ["renewal", "renew", "begin", "fresh", "refresh", "clean", "cleanse"],
  },
  {
    img: "images/deep cycle H/sensitive.jpg",
    name: "sensitive",
    models: ["all", "resonance-plus", "pro"],
    tags: ["sensitive", "sensitivity"],
  },
  //DEEP CYCLE H
  //FITNESS
  {
    img: "images/fitness/circulation.jpg",
    name: "circulation",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["circulation", "circulate", "flow", "fitness"],
  },
  {
    img: "images/fitness/deep relaxation.jpg",
    name: "deep relaxation",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "deep",
      "relaxation",
      "relax",
      "refresh",
      "calm",
      "peace",
      "fitness",
    ],
  },
  {
    img: "images/fitness/muscle harmony.jpg",
    name: "muscle harmony",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "muscle",
      "harmony",
      "muscles",
      "fitness",
      "exercise",
      "work",
      "out",
      "fitness",
    ],
  },
  {
    img: "images/fitness/performance.jpg",
    name: "performance",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "performance",
      "perform",
      "optimal",
      "potential",
      "aptitude",
      "result",
      "results",
      "fitness",
    ],
  },
  {
    img: "images/fitness/regeneration.jpg",
    name: "regeneration",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "regeneration",
      "regenerate",
      "renew",
      "fresh",
      "refresh",
      "align",
      "alignment",
      "cleanse",
      "clear",
      "fitness",
    ],
  },
  {
    img: "images/fitness/stamina.jpg",
    name: "stamina",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["stamina", "endurance", "out", "last", "fortify", "fitness"],
  },
  {
    img: "images/fitness/strength.jpg",
    name: "strength",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["strength", "strengthen", "power", "force", "fitness"],
  },
  {
    img: "images/fitness/weight.jpg",
    name: "weight",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["weight", "gain", "loss", "fat", "muscle", "muscles", "fitness"],
  },
  //FITNESS
  //GOLD CYCLE
  {
    img: "images/gold cycle/balance.jpg",
    name: "balance",
    models: ["all", "gold", "resonance-plus", "pro"],
    tags: ["balance", "stability", "stable", "center", "equal", "equilibrium"],
  },
  {
    img: "images/gold cycle/being.jpg",
    name: "being",
    models: ["all", "gold", "resonance-plus", "pro"],
    tags: [
      "being",
      "now",
      "moment",
      "calm",
      "peace",
      "center",
      "align",
      "alignment",
    ],
  },
  {
    img: "images/gold cycle/care.jpg",
    name: "care",
    models: ["all", "gold", "resonance-plus", "pro"],
    tags: [
      "care",
      "love",
      "caring",
      "connecting",
      "connection",
      "nurture",
      "nurturing",
    ],
  },
  {
    img: "images/gold cycle/energy.jpg",
    name: "energy",
    models: ["all", "gold", "resonance-plus", "pro"],
    tags: [
      "energy",
      "pure",
      "up",
      "lifting",
      "power",
      "strength",
      "strengthen",
    ],
  },
  {
    img: "images/gold cycle/pure.jpg",
    name: "pure",
    models: ["all", "gold", "resonance-plus", "pro"],
    tags: [
      "pure",
      "impurities",
      "purify",
      "clean",
      "clear",
      "cleanse",
      "remove",
    ],
  },
  {
    img: "images/gold cycle/relax.jpg",
    name: "relax",
    models: ["all", "gold", "resonance-plus", "pro"],
    tags: ["relax", "relaxing", "relaxation", "refresh", "calm", "peace"],
  },
  {
    img: "images/gold cycle/release.jpg",
    name: "release",
    models: ["all", "gold", "resonance-plus", "pro"],
    tags: ["release", "let", "go", "clean", "cleanse", "pure", "purify"],
  },
  //FITNESS
  //JOB AND SLEEP
  {
    img: "images/job and sleep/balanced sleep.jpg",
    name: "balanced sleep",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "balanced",
      "sleep",
      "rest",
      "deep",
      "equal",
      "equilibrium",
      "rejuvenate",
    ],
  },
  {
    img: "images/job and sleep/bed rest.jpg",
    name: "bed rest",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["bed", "rest", "sleep", "rest", "deep", "rejuvenate"],
  },
  {
    img: "images/job and sleep/fine flow.jpg",
    name: "fine flow",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["fine", "flow", "aptitude", "performance", "refined", "optimal"],
  },
  {
    img: "images/job and sleep/sleep syst.jpg",
    name: "sleep systemic",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["sleep", "systemic", "deep", "rest", "rejuvenate"],
  },
  //JOB AND SLEEP
  //LEARNING
  {
    img: "images/learning/concentration acute.jpg",
    name: "concentration acute",
    models: ["all", "resonance-plus", "pro"],
    tags: ["concentration", "acute", "focus"],
  },
  {
    img: "images/learning/concentration syst.jpg",
    name: "concentration systemic",
    models: ["all", "resonance-plus", "pro"],
    tags: ["concentration", "systemic", "focus"],
  },
  {
    img: "images/learning/exam acute.jpg",
    name: "exam acute",
    models: ["all", "resonance-plus", "pro"],
    tags: ["exam", "acute", "focus", "learn", "learning", "performance"],
  },
  {
    img: "images/learning/exam syst.jpg",
    name: "exam systemic",
    models: ["all", "resonance-plus", "pro"],
    tags: ["exam", "systemic", "focus", "learn", "learning", "performance"],
  },
  {
    img: "images/learning/learning acute.jpg",
    name: "learning acute",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "learning",
      "acute",
      "focus",
      "learn",
      "learning",
      "performance",
      "concentration",
    ],
  },
  {
    img: "images/learning/learning syst.jpg",
    name: "learning systemic",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "learning",
      "systemic",
      "focus",
      "learn",
      "learning",
      "performance",
      "concentration",
    ],
  },
  {
    img: "images/learning/memory.jpg",
    name: "memory",
    models: ["all", "resonance-plus", "pro"],
    tags: ["memory", "remember", "retain", "retention", "recall", "focus"],
  },
  {
    img: "images/learning/stress acute.jpg",
    name: "stress acute",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "stress",
      "acute",
      "stressful",
      "relive",
      "reliving",
      "relax",
      "relaxing",
      "calm",
      "calming",
    ],
  },
  {
    img: "images/learning/stress syst.jpg",
    name: "stress systemic",
    models: ["all", "resonance-plus", "pro"],
    tags: [
      "stress",
      "systemic",
      "stressful",
      "relive",
      "reliving",
      "relax",
      "relaxing",
      "calm",
      "calming",
    ],
  },
  //LEARNING
  //MENTAL BALANCE
  {
    img: "images/mental balance/contentment acute.jpg",
    name: "contentment acute",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "contentment",
      "acute",
      "peace",
      "calm",
      "relax",
      "relaxing",
      "balance",
    ],
  },
  {
    img: "images/mental balance/contentment syst.jpg",
    name: "contentment systemic",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "contentment",
      "systemic",
      "peace",
      "calm",
      "relax",
      "relaxing",
      "balance",
    ],
  },
  {
    img: "images/mental balance/emotional wellbeing.jpg",
    name: "emotional wellbeing",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "emotional",
      "wellbeing",
      "peace",
      "calm",
      "ease",
      "relax",
      "relaxing",
    ],
  },
  {
    img: "images/mental balance/feel good syst.jpg",
    name: "feel good systemic",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["feel", "good", "systemic", "peace", "calm", "enjoy", "enjoyment"],
  },
  {
    img: "images/mental balance/inner strength syst.jpg",
    name: "inner strength systemic",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "inner",
      "strength",
      "systemic",
      "strengthen",
      "fortify",
      "perseverance",
    ],
  },
  {
    img: "images/mental balance/inner unity.jpg",
    name: "inner unity",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "inner",
      "unity",
      "oneness",
      "connection",
      "connecting",
      "center",
      "balance",
    ],
  },
  {
    img: "images/mental balance/mental balance acute.jpg",
    name: "mental balance acute",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "mental",
      "balance",
      "acute",
      "mind",
      "brain",
      "fog",
      "focus",
      "center",
      "equal",
      "equilibrium",
    ],
  },
  {
    img: "images/mental balance/wellbeing soul.jpg",
    name: "wellbeing soul",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "wellbeing",
      "soul",
      "peace",
      "calm",
      "care",
      "love",
      "relax",
      "relaxing",
    ],
  },
  //MENTAL BALANCE
  //MERIDIANS 1
  {
    img: "images/meridians 1/allergy meridian.jpg",
    name: "allergy meridian",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["allergy", "meridian", "meridians", "allergic", "clear", "cleanse"],
  },
  {
    img: "images/meridians 1/bladder.jpg",
    name: "bladder",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "bladder",
      "urine",
      "urinate",
      "organ",
      "organs",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/connective tissue.jpg",
    name: "connective tissue",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "connective",
      "tissue",
      "body",
      "movement",
      "move",
      "flexible",
      "flexibility",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/fatty degeneration.jpg",
    name: "fatty degeneration",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "fatty",
      "degeneration",
      "degenerate",
      "break",
      "down",
      "eliminate",
      "weight",
      "loss",
      "tone",
      "refine",
      "slim",
      "fit",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/gall bladder.jpg",
    name: "gall bladder",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "gall",
      "bladder",
      "liver",
      "digestion",
      "digest",
      "organ",
      "organs",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/heart.jpg",
    name: "heart",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "heart",
      "blood",
      "circulate",
      "circulation",
      "organ",
      "organs",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/joints.jpg",
    name: "joints",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "joints",
      "flexible",
      "flexibility",
      "stiff",
      "sore",
      "arthritis",
      "meridian",
      "meridians",
    ],
  },
  {
    img: "images/meridians 1/large intestine.jpg",
    name: "large intestine",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "meridian",
      "meridians",
      "large",
      "intestine",
      "gut",
      "gi",
      "digest",
      "digestion",
      "organ",
      "organs",
    ],
  },
  {
    img: "images/meridians 1/skin harmony.jpg",
    name: "skin harmony",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "skin", "harmony", "organ", "organs"],
  },
  {
    img: "images/meridians 1/small intestine.jpg",
    name: "small intestine",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "meridian",
      "meridians",
      "small",
      "intestine",
      "gut",
      "gi",
      "digest",
      "digestion",
      "organ",
      "organs",
    ],
  },
  //MERIDIANS 1
  //MERIDIANS 2
  {
    img: "images/meridians 2/circulation.jpg",
    name: "circulation",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: [
      "meridian",
      "meridians",
      "circulation",
      "blood",
      "circulate",
      "flow",
    ],
  },
  {
    img: "images/meridians 2/hormonal balance.jpg",
    name: "hormonal balance",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "hormonal", "hormone", "balance"],
  },
  {
    img: "images/meridians 2/kidney.jpg",
    name: "kidney",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "kidney", "organ", "organs"],
  },
  {
    img: "images/meridians 2/liver.jpg",
    name: "liver",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "liver", "organ", "organs"],
  },
  {
    img: "images/meridians 2/lungs.jpg",
    name: "lungs",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "lungs", "organ", "organs"],
  },
  {
    img: "images/meridians 2/lymphatic system.jpg",
    name: "lymphatic system",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "lymphatic", "system"],
  },
  {
    img: "images/meridians 2/nerve meridian.jpg",
    name: "nerve meridian",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "nerve"],
  },
  {
    img: "images/meridians 2/organ meridian.jpg",
    name: "organ meridian",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "organ", "organs"],
  },
  {
    img: "images/meridians 2/spleen-pancreas.jpg",
    name: "spleen-pancreas",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "spleen", "pancreas", "organ", "organs"],
  },
  {
    img: "images/meridians 2/stomach.jpg",
    name: "stomach",
    models: ["all", "holistic", "resonance", "resonance-plus", "pro"],
    tags: ["meridian", "meridians", "stomach", "organ", "organs"],
  },
  //MERIDIANS 2
  //PAIN STIM
  {
    img: "images/pain stim/III.jpg",
    name: "III",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["pain", "stimulation", "III"],
  },
  {
    img: "images/pain stim/IV.jpg",
    name: "IV",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["pain", "stimulation", "IV"],
  },
  {
    img: "images/pain stim/pain locally.jpg",
    name: "pain locally",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["pain", "stimulation", "locally", "local"],
  },
  {
    img: "images/pain stim/pain.jpg",
    name: "pain",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["pain", "stimulation"],
  },
  {
    img: "images/pain stim/V.jpg",
    name: "V",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["pain", "stimulation", "V"],
  },
  {
    img: "images/pain stim/VI.jpg",
    name: "VI",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["pain", "stimulation", "VI"],
  },
  {
    img: "images/pain stim/VII.jpg",
    name: "VII",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["pain", "stimulation", "VII"],
  },
  {
    img: "images/pain stim/VIII.jpg",
    name: "VIII",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["pain", "stimulation", "VIII"],
  },
  //PAIN STIM
  //THE POWER OF THREE
  {
    img: "images/the power of three/conflict balance.jpg",
    name: "conflict balance",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["the", "power", "of", "three", "conflict", "balance"],
  },
  {
    img: "images/the power of three/defense support.jpg",
    name: "defense support",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["the", "power", "of", "three", "defense", "support"],
  },
  {
    img: "images/the power of three/friendly flora.jpg",
    name: "friendly flora",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["the", "power", "of", "three", "friendly", "flora"],
  },
  {
    img: "images/the power of three/kapha.jpg",
    name: "kapha",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["the", "power", "of", "three", "kapha"],
  },
  {
    img: "images/the power of three/pita.jpg",
    name: "pita",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["the", "power", "of", "three", "pita"],
  },
  {
    img: "images/the power of three/rebalance.jpg",
    name: "rebalance",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["the", "power", "of", "three", "rebalance"],
  },
  {
    img: "images/the power of three/rife energetic.jpg",
    name: "rife energetic",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["the", "power", "of", "three", "rife", "energetic"],
  },
  {
    img: "images/the power of three/rife physical.jpg",
    name: "rife physical",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["the", "power", "of", "three", "rife", "physical"],
  },
  {
    img: "images/the power of three/vata.jpg",
    name: "vata",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: ["the", "power", "of", "three", "vata"],
  },
  {
    img: "images/the power of three/zapper protocol.jpg",
    name: "zapper protocol",
    models: ["all", "resonance", "resonance-plus", "pro"],
    tags: [
      "the",
      "power",
      "of",
      "three",
      "zapper",
      "protocol",
      "parasite",
      "parasite cleanse",
    ],
  },
];
